---
- name: "Configure the CSESoc Account"
  hosts: all
  tasks:
    - name: "Clear existing public_html"
      file:
        path: '~/public_html'
        state: absent

    - name: Clone the CGI Script Repo
      git:
        repo: https://github.com/csesoc/cse-cgi-scripts.git
        dest: ~/public_html

- name: "Configure UDB htaccess"
  hosts: all
  tags: secrets
  roles:
    - name: local.htpasswd
      entries: "{{ secrets.udb_entries }}"
      dest: '~/public_html/udb/.htpasswd'
