# This playbook configures the SSH authorised keys of the current ansible user.
---
- name: Configure Authorized Keys
  hosts: all
  tags: security
  vars:
    authorized_keys:
      # Nick Whyte
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCzhFQmx3gz+fSiTgqguRYskIrOzuYteTIRLIom7jFQSRcxIiIozX/FMOyFpc7ASmy9FNvlUzjZEcgOoTjdflUTDWp8N61pjcpO3n8FEGe7Ine7HOpbIC6ghWeDNS4nyg3Tsk3cK2kLTXBdKk+gGU7ZnvT7WzehlLLVNpnnUqmdVmy4OU4yRQ6Fvs+lVVcEkCpIa83oqLX6w/nNxv3mVXrdPYtluCOLJ/dajZht5zFLOY6hJSPuVxwy2oRSzmrSh+Dn0tBr9C5H8QtEUgHm0s4k7gHn6ivAopqyfU0WvPgiIrLPwmXysCzxrOiiXoXAT4p6bJj5W/ei62FejEeBbZTn nickw@pro.home-feb-2016
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/5tFquHcGRtHJWy6aq2bg4ivCU4TLF7QX94FZNScWGL5Xle7GZS5519u+GGFo1IObDovGUTe0nz9hOXHigc+6ABia4QSsd/lzVvp0EnqysiCnhRpzS4miTUmH4v46ubNFiQ/eGXSXG7pAO7ozLBsLpnEdxxf/BBr8MF8wCSI3KKTMKBhy6KlM/klwucsn6042OFlszmhNuSn/JK2ZKl2qAFSTEBo1qBnCVtJjrDU89F0R7BnR8/835K809o52/muKrFAGITZF2rvb7kZmGMH19aN7qP5kHBsnOLcinuL0sdGMHjCfxVQchernMTQ6olvVF0xzXC9vanKcRziYHMB3 nickw@canva
      # Ofir Zeevi
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDZSwkUzQJDei09xRexZ3UoQk8Hfjl3v0nfyTzjcn7CNYEy8N7Win+t7dI4xx+qDATfw8Aa9P1llT3MdJdLgxAlEYUdXARh/MSuTlTOjpCNF2VCBLX1npHQN/EzSSHV5v8YXi2z7wpBJnGh9iZn43+NDaQxE4PAGBitvKGrsujE8leRr/is0MI2dtObWOHNE5kGG/xTmv0eLr+I1PFuJlDcfiRrnK2JMGe8XJ4bMtcu+nL6Ug5bNdBz3GFUqd2rnXNaimi/pXcVywPWjUbwbJfnkkDP1e0i4OzeTli41WENeEjZCnkSLGg//MIOKqQoLKzG/HjPuC9X/ivSl31Syx9n Zeevi@Ofirs-MacBook-Pro.local
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDp7fy2nuFZ/8tGRBVmbF3xR8zUmzK4L3lqhm8wVr9z3IeKI4OiupgA/F8O2BAIzmYqc3yvWNorRSTqORZsOetvCh/fZmzUWT7lNQ4rS3SNMQCUr0ehj1pUQPU4SRYN9rYloNwkdIR+rySr58aTUw5bPQxLvlX6dUA11sWTfOXWndmzgjP6ayNwAFiW6a6EFdHDvnwhGLJ/vXG7VccFBB59RQBHhSrzB0Lvb845fpk58/rYaFScOfg9j2awa7zRzNYaH8yjIwbn3IWlmCjA9w4VfWZMRbdVBpsCZ8nQtIQoh1i5e8qF0lh+HO15Wr3jgbKDW/aieBJY++omjULOA+tZ z5117227@weill
      # Celine Tye
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCq3D5+EcuiXTrq8UWUEQT4G74C3Az3HHqedyA+zvii9uUCGf56K0Tfhmwp0o/DcSsuYK/CS0dRaD7ejjz0L62DQ2Uj0GzgfVY0o26MVeJs2RqakHC6VnKRwfsV9HJYK/RHGWIWV20el0ujfpeRveFRUsbSWfMZ+TBT8iwOF7vN2u5K3Z6on8K7AwuZqPFuJpzUYUpYzEIc1YUD7WXiEWO44k1ralfhj0T835W9Tc/JKhOfV/9af2eGAiPeVA3QDGBFg5i9HNsmD6phT8FDFVOgJACp/119zBQaxn74efdrxIYfUD5esy5jEWQOC5kS85aTHj2j4bwFqVq55YNdRuKr celine@celine-UX31A
  tasks:
    - name: "Install Keys"
      authorized_key:
        exclusive: yes
        user: "{{ ansible_user }}"
        key: "{{ '\n'.join(authorized_keys + extra_authorized_keys) }}"
