---
- name: Add data dir
  hosts: wheatley
  tasks:
    - name: Add data dir
      file:
        path: /containers/data/
        state: directory

- hosts: wheatley
  name: Configure container data backups
  tags: backups
  become: root
  tasks:
    - name: Add profile bin dir
      file:
        path: ~/bin/
        state: directory
    - name: Copy backup job script
      copy:
        src: backup.sh
        dest: ~/bin/backup.sh
        mode: +x
    - name: Copy backup container job script
      copy:
        src: backup-container-data.sh
        dest: ~/bin/backup-container-data.sh
        mode: +x
    - name: Copy backup rancher job script
      copy:
        src: backup-rancher-data.sh
        dest: ~/bin/backup-rancher-data.sh
        mode: +x
    - name: Copy restore backup rancher job script
      copy:
        src: restore-backup.sh
        dest: ~/bin/restore-backup.sh
        mode: +x
    - name: Copy restore backup rancher job script
      copy:
        src: restore-backup.sh
        dest: ~/bin/restore-backup.sh
        mode: +x
    - name: Add healthcheck UUID
      lineinfile:
        path: /etc/environment
        regexp: '^HEALTHCHECK_UUID'
        insertafter: '^PATH.*'
        line: 'HEALTHCHECK_UUID={{ cron_healthcheck_uuid_container_data }}'
    - name: Add nightly cron job
      cron:
        name: "backup container data"
        hour: 1
        minute: 0
        job: ~/bin/backup.sh

- name: Setup Rancher UI
  tags: rancher
  hosts: wheatley
  tasks:
    - name: Copy rancher certificates
      copy:
        src: ssl/certs
        dest: /var/lib/rancher/etc/ssl/
    - docker_container:
        name: rancher
        image: rancher/rancher:stable
        state: started
        pull: yes
        recreate: yes
        published_ports:
          - 7654:7654
        restart_policy: unless-stopped
        volumes:
          - /var/lib/rancher/etc/ssl/wheatley.cacerts.pem:/etc/rancher/ssl/cacerts.pem
          - /var/lib/rancher/etc/ssl/wheatley.fullchain.pem:/etc/rancher/ssl/cert.pem
          - /var/lib/rancher/etc/ssl/wheatley.key:/etc/rancher/ssl/key.pem

