---
- name: Add data dir
  hosts: all
  tasks:
    - name: Add data dir
      file:
        path: /containers/data/
        state: directory

- hosts: all
  name: Configure container data backups
  tags: backups
  become: root
  tasks:
    - name: Add profile bin dir
      file:
        path: ~/bin/
        state: directory
    - name: Copy backup job script
      copy:
        src: backup-container-data.sh
        dest: ~/bin/backup-container-data.sh
        mode: +x
    - name: Add nightly cron job
      cron:
        name: "backup container data"
        hour: 0
        minute: 0
        job: ~/bin/backup-container-data.sh && curl -fsS --retry 3 https://hchk.io/{{ cron_healthcheck_uuid_container_data }} > /dev/null

- name: Setup Rancher UI
  tags: rancher
  hosts: all
  tasks:
    - name: Copy rancher root certificate
      copy:
        src: rancher-nginx/ssl/certs/wheatley.cse.unsw.edu.au.bundle.crt
        dest: /var/lib/rancher/etc/ssl/ca.crt
    - name: Copy nginx config
      copy:
        src: rancher-nginx
        dest: /containers/conf/
    - docker_container:
        name: rancher
        image: rancher/server:stable
        state: started
        pull: yes
        recreate: yes
        restart_policy: unless-stopped
        volumes:
          - /containers/data/rancher:/var/lib/mysql
          - /var/lib/rancher/etc/ssl/ca.crt:/var/lib/rancher/etc/ssl/ca.crt
    - name: Add Nginx Container
      docker_container:
        name: nginx
        image: nginx
        state: started
        recreate: yes
        pull: yes
        restart_policy: always
        published_ports:
          - 7654:7654
        links:
          - rancher:rancher
        volumes:
          - /containers/conf/rancher-nginx/conf.d:/etc/nginx/conf.d
          - /containers/conf/rancher-nginx/ssl:/etc/nginx/ssl
