version: '2'
services:
  csesoc-website:
    image: csesoc/csesoc-website-v2
    environment:
      SECRET_KEY: XXX
      STRIPE_SKEY: XXX
      STRIPE_PKEY: XXX
      NEVERCACHE_KEY: XXX
    stdin_open: true
    volumes:
    - /containers/data/csesoc-website:/app/data
    tty: true
    labels:
      io.rancher.container.pull_image: always
  www-redirect:
    image: cusspvz/redirect
    environment:
      REDIRECT: https://www.csesoc.unsw.edu.au
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  media-admin:
    image: hacdias/filebrowser
    stdin_open: true
    volumes:
    - /containers/data/csesoc-website/media:/srv
    - /containers/data/csesoc-website-file-browser/database.db:/etc/database.db
    tty: true
    command:
    - --baseurl
    - /media-admin
    labels:
      io.rancher.container.pull_image: always
  load-balancer:
    image: rancher/lb-service-haproxy:v0.9.1
    expose:
    - 80:80/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
