version: '2'
services:
  csesoc-website:
    scale: 1
    start_on_create: true
  www-redirect:
    scale: 1
    start_on_create: true
  media-admin:
    scale: 1
    start_on_create: true
  load-balancer:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: www.csesoc.unsw.edu.au
        path: /media-admin
        priority: 1
        protocol: http
        service: media-admin
        source_port: 80
        target_port: 80
      - hostname: www.csesoc.unsw.edu.au
        path: ''
        priority: 2
        protocol: http
        service: csesoc-website
        source_port: 80
        target_port: 8080
      - hostname: ''
        path: ''
        priority: 3
        protocol: http
        service: www-redirect
        source_port: 80
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
